export const images = {
    logo: require("./logo.svg").default,
    intro_desktop: require("./image-intro-desktop.jpg"),
    intro_mobile: require("./image-intro-mobile.jpg"),
    intro_left: require("./bg-pattern-intro-left-desktop.svg").default,
    intro_left_mobile: require("./bg-pattern-intro-left-mobile.svg").default,
    intro_right: require("./bg-pattern-intro-right-desktop.svg").default,
    intro_right_mobile: require("./bg-pattern-intro-right-mobile.svg").default,
    snappy_process: require("./icon-snappy-process.svg").default,
    people_first: require("./icon-people-first.svg").default,
    affordable_prices: require("./icon-affordable-prices.svg").default,
    works_desktop: require("./bg-pattern-how-we-work-desktop.svg").default,
    works_mobile: require("./bg-pattern-how-we-work-mobile.svg").default,
    fb: require("./icon-facebook.svg").default,
    twitter: require("./icon-twitter.svg").default,
    pinterest: require("./icon-pinterest.svg").default,
    insta: require("./icon-instagram.svg").default,
    footer: require("./bg-pattern-footer-desktop.svg").default,
    footer_mob: require("./bg-pattern-footer-mobile.svg").default,
    hamburger: require("./icon-hamburger.svg").default,
    category1: require("./image1.jpg"),
    category2: require("./image2.jpg"),
    car: require("./car1.png"),
    bike: require("./bike1.png"),
    featurebasic1:require("./featurebasic1.png"),
    featurebasic2:require("./featurebasic2.png"),
    featurebasic3:require("./featurebasic3.png"),
    featuregold1:require("./featuregold1.png"),
    featuregold2:require("./featuregold2.png"),
    featuregold3:require("./featuregold3.png"),
    featureplatinum1:require("./featureplatinum1.png"),
    featureplatinum2:require("./featureplatinum2.png"),
    featureplatinum3:require("./featureplatinum3.png"),
};
